backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# publish_mode: editorial_workflow

media_folder: "img/uploads" # Media files will be stored in the repo under images/uploads

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "About"
        name: "about"
        file: "about.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
      - label: "Commercial"
        name: "commerical"
        file: "commercial.html"
        fields:
          - label: Intro
            name: intro
            widget: string
      - label: "Test"
        name: "test"
        file: "_data/test.yml"
        fields:
          - label: Title
            name: title
            widget: string
          - label: Description
            name: description
            widget: string
          - label: Permalink
            name: permalink
            widget: string
          - label: Intro
            name: intro
            widget: string

