backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# publish_mode: editorial_workflow

media_folder: "img/uploads" # Media files will be stored in the repo under images/uploads

collections:
  - label: "Pages"
    name: "pages"
    files:
